ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
minimumReleaseAgeExclude:
  - '@types/node@25.9.1'
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - examples/*

allowBuilds:
  core-js: true
  esbuild: true
